In [1]:
import numpy

arr = numpy.array([1, 2, 3, 4, 5])

print(arr)

[1 2 3 4 5]


In [4]:
import numpy as np

arr = np.array([1, 2, 3, 4])

print(arr[0])
print(arr[1])
print(arr[2] + arr[3])


1
2
7


In [7]:
import numpy as np

arr = np.array([[11,22,33,44,55], [66,77,88,99,1010]])

print('2nd element on 1st row: ', arr[0, 1])
print('5th element on 2nd row: ', arr[1, 4])

2nd element on 1st row:  22
5th element on 2nd row:  1010


In [8]:
import numpy as np

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

print(arr[0, 1, 2])

6


In [9]:
import numpy as np

arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print('Last element from 2nd dim: ', arr[1, -1])

Last element from 2nd dim:  10


In [12]:
import numpy as np

arr = np.array([111, 222, 333, 444, 555, 655, 777])

print(arr[1:5])
print(arr[4:])
print(arr[:5])
print(arr[-3:-1])
print(arr[1:5:2])
print(arr[::2])

[222 333 444 555]
[555 655 777]
[111 222 333 444 555]


In [ ]:
                                              Slicing 2-D Arrays

In [14]:
import numpy as np

arr = np.array([[1111, 2222, 3333, 4444, 5555], [6666, 7777, 8888, 9999, 10101]])

print(arr[0:2, 2])
print(arr[0:2, 1:4])
print(arr.dtype)

[3333 8888]
[[2222 3333 4444]
 [7777 8888 9999]]
int64


In [15]:
import numpy as np

arr = np.array(['apple', 'banana', 'cherry'])

print(arr.dtype)

<U6


In [17]:
import numpy as np

arr = np.array([1, 2, 3, 4], dtype='S')
arr = np.array([1, 2, 3, 4], dtype='i4')

print(arr)
print(arr.dtype)

[1 2 3 4]
int32


In [18]:
import numpy as np

arr = np.array([1111.1, 22222.1, 3333.1])

newarr = arr.astype('i')

print(newarr)
print(newarr.dtype)

[ 1111 22222  3333]
int32


In [19]:
import numpy as np

arr = np.array([1, 0, 3])

newarr = arr.astype(bool)

print(newarr)
print(newarr.dtype)

[ True False  True]
bool


In [ ]:
                                                 copy va view

In [20]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
x = arr.view()
arr[0] = 42

print(arr)
print(x)

[42  2  3  4  5]
[42  2  3  4  5]


In [21]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
x = arr.view()
x[0] = 31

print(arr)
print(x)

[31  2  3  4  5]
[31  2  3  4  5]


In [22]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

x = arr.copy()
y = arr.view()

print(x.base)
print(y.base)

None
[1 2 3 4 5]


In [23]:
import numpy as np

arr = np.array([[101010, 202020, 303030, 4404040], [5505, 6606, 7707, 8808]])

print(arr.shape)

(2, 4)


In [24]:
import numpy as np

arr = np.array([123456789, 2345678910, 34567891011, 456789101112], ndmin=5)

print(arr)
print('shape of array :', arr.shape)

[[[[[   123456789   2345678910  34567891011 456789101112]]]]]
shape of array : (1, 1, 1, 1, 4)


In [ ]:
                                                Reshape From 1-D to 2-D

In [27]:
import numpy as np

arr = np.array([101, 202, 303, 404, 505, 606, 707, 808, 909, 10010, 11011, 12012])

newarr = arr.reshape(2, 3, 2)

print(newarr)


[[[  101   202]
  [  303   404]
  [  505   606]]

 [[  707   808]
  [  909 10010]
  [11011 12012]]]


In [29]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

print(arr.reshape(2, 4).base)

[1 2 3 4 5 6 7 8]


In [30]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

newarr = arr.reshape(2, 2, -1)

print(newarr)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [ ]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])

newarr = arr.reshape(-1)

print(newarr)